name: solaris
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.35.0
  shared_preferences: ^2.0.9
  path_provider: ^2.0.2
  sqflite: ^2.0.0+3
  

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  flutter_test:
    sdk: flutter
  image_picker: ^0.8.4+2
  flutter_launcher_icons: ^0.13.1

flutter:
  assets:
    - assets/fundo.jpg
    - assets/logo.jpg
    - assets/back_arrow.png
flutter_icons:
  android: true
  ios: true
  image_path: "assets/back_arrow.png" # Caminho para o seu ícone
